"""empty message

Revision ID: 41035430c400
Revises: 47e30c4ec092
Create Date: 2022-04-19 10:48:39.219486

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '41035430c400'
down_revision = '47e30c4ec092'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column('alunni', sa.Column('esito_finale_norm', sa.String(length=128), nullable=True))
    op.add_column('alunni', sa.Column('indirizzo_studi_norm', sa.String(length=128), nullable=True))
    op.add_column('alunni', sa.Column('sede_norm', sa.String(length=128), nullable=True))
    # op.drop_index('idx_indirizzo_geom_dev', table_name='indirizzo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('idx_indirizzo_geom_dev', 'indirizzo', ['geom'], unique=False)
    op.drop_column('alunni', 'sede_norm')
    op.drop_column('alunni', 'indirizzo_studi_norm')
    op.drop_column('alunni', 'esito_finale_norm')
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    # ### end Alembic commands ###
