"""collegamenti forzati

Revision ID: 4cf22a50c7e3
Revises: d2b143fbceb3
Create Date: 2026-09-08 16:16:47.677977

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2          # serve alle colonne `geom`; lascialo anche se inutilizzato


# revision identifiers, used by Alembic.
revision = '4cf22a50c7e3'
down_revision = 'd2b143fbceb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rel_alunno_strada', sa.Column('forzato', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rel_alunno_strada', 'forzato')
    # ### end Alembic commands ###
