"""empty message

Revision ID: 570c1f9f1617
Revises: 812c6aca0e7a
Create Date: 2025-02-25 11:11:32.952603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '570c1f9f1617'
down_revision = '812c6aca0e7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    # op.drop_index('idx_strada_geom_add', table_name='strada')
    op.add_column('user', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('current_login_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('last_login_ip', sa.String(), nullable=True))
    op.add_column('user', sa.Column('current_login_ip', sa.String(), nullable=True))
    op.add_column('user', sa.Column('login_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'login_count')
    op.drop_column('user', 'current_login_ip')
    op.drop_column('user', 'last_login_ip')
    op.drop_column('user', 'current_login_at')
    op.drop_column('user', 'last_login_at')
    # op.create_index('idx_strada_geom_add', 'strada', ['geom'], unique=False)
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    # ### end Alembic commands ###
