"""empty message

Revision ID: 5995aed57009
Revises: 41035430c400
Create Date: 2025-02-18 11:37:27.169932

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '5995aed57009'
down_revision = '41035430c400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('osm_road', sa.String(length=128), nullable=True),
    sa.Column('osm_house_number', sa.String(length=128), nullable=True),
    sa.Column('osm_house_number_dev', sa.String(length=128), nullable=True),
    sa.Column('osm_postcode', sa.String(length=128), nullable=True),
    sa.Column('osm_suburb', sa.String(length=128), nullable=True),
    sa.Column('osm_city', sa.String(length=128), nullable=True),
    sa.Column('osm_type', sa.String(length=128), nullable=True),
    sa.Column('osm_lat', sa.Float(), nullable=True),
    sa.Column('osm_lon', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_strada_geom_add', 'strada', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_table('rel_alunno_strada',
    sa.Column('alunno_id', sa.Integer(), nullable=False),
    sa.Column('strada_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alunno_id'], ['alunni.id'], ),
    sa.ForeignKeyConstraint(['strada_id'], ['strada.id'], ),
    sa.PrimaryKeyConstraint('alunno_id', 'strada_id')
    )
    # op.drop_table('spatial_ref_sys')
    op.add_column('alunni', sa.Column('via', sa.String(length=128), nullable=True))
    op.add_column('alunni', sa.Column('punteggio_esame', sa.String(length=128), nullable=True))
    op.drop_index('idx_indirizzo_geom_dev', table_name='indirizzo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_indirizzo_geom_dev', 'indirizzo', ['geom'], unique=False)
    op.drop_column('alunni', 'punteggio_esame')
    op.drop_column('alunni', 'via')
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    op.drop_table('rel_alunno_strada')
    op.drop_index('idx_strada_geom', table_name='strada', postgresql_using='gist', postgresql_ops={})
    op.drop_table('strada')
    # ### end Alembic commands ###
