"""empty message

Revision ID: 812c6aca0e7a
Revises: 5995aed57009
Create Date: 2025-02-18 19:36:14.625562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '812c6aca0e7a'
down_revision = '5995aed57009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.drop_constraint('alunni_id_alunno_fkey', 'alunni', type_='foreignkey')
    # op.drop_index('idx_strada_geom_add', table_name='strada')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('idx_strada_geom_add', 'strada', ['geom'], unique=False)
    op.create_foreign_key('alunni_id_alunno_fkey', 'alunni', 'indirizzo', ['id_alunno'], ['id_alunno'])
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    # ### end Alembic commands ###
