"""empty message

Revision ID: b0440bf1454c
Revises: 570c1f9f1617
Create Date: 2025-02-25 15:13:02.624747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0440bf1454c'
down_revision = '570c1f9f1617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    with op.batch_alter_table('strada', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_create', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('data_update', sa.DateTime(), nullable=True))
        # batch_op.drop_index('idx_strada_geom_add', postgresql_using='gist')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strada', schema=None) as batch_op:
        # batch_op.create_index('idx_strada_geom_add', ['geom'], unique=False, postgresql_using='gist')
        batch_op.drop_column('data_update')
        batch_op.drop_column('data_create')

    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    # ### end Alembic commands ###
