"""schema iniziale

Revision ID: d2b143fbceb3
Revises: 
Create Date: 2026-09-01 18:38:53.315963

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2          # necessario: le colonne `geom` sono di questo tipo


# revision identifiers, used by Alembic.
revision = 'd2b143fbceb3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indirizzo',
    sa.Column('id_alunno', sa.Integer(), nullable=False),
    sa.Column('osm_indirizzo_ref', sa.String(length=128), nullable=True),
    sa.Column('osm_road', sa.String(length=128), nullable=True),
    sa.Column('osm_house_number', sa.String(length=128), nullable=True),
    sa.Column('osm_house_number_dev', sa.String(length=128), nullable=True),
    sa.Column('osm_postcode', sa.String(length=128), nullable=True),
    sa.Column('osm_suburb', sa.String(length=128), nullable=True),
    sa.Column('osm_city', sa.String(length=128), nullable=True),
    sa.Column('osm_lat', sa.Float(), nullable=True),
    sa.Column('osm_lon', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id_alunno')
    )
    op.create_table('strada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('osm_road', sa.String(length=128), nullable=True),
    sa.Column('osm_house_number', sa.String(length=128), nullable=True),
    sa.Column('osm_house_number_dev', sa.String(length=128), nullable=True),
    sa.Column('osm_postcode', sa.String(length=128), nullable=True),
    sa.Column('osm_suburb', sa.String(length=128), nullable=True),
    sa.Column('osm_city', sa.String(length=128), nullable=True),
    sa.Column('osm_type', sa.String(length=128), nullable=True),
    sa.Column('osm_lat', sa.Float(), nullable=True),
    sa.Column('osm_lon', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('data_create', sa.DateTime(), nullable=True),
    sa.Column('data_update', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stradario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=256), nullable=False),
    sa.Column('nome_norm', sa.String(length=256), nullable=False),
    sa.Column('comune', sa.String(length=128), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('osm_ids', sa.Integer(), nullable=True),
    sa.Column('data_update', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', 'comune', name='uq_stradario_nome_comune')
    )
    op.create_index(op.f('ix_stradario_comune'), 'stradario', ['comune'], unique=False)
    op.create_index(op.f('ix_stradario_nome_norm'), 'stradario', ['nome_norm'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_clear', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('interest', sa.Text(), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('current_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(), nullable=True),
    sa.Column('current_login_ip', sa.String(), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('alunni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anno_ref', sa.String(length=128), nullable=True),
    sa.Column('id_alunno', sa.Integer(), nullable=True),
    sa.Column('sesso', sa.String(length=128), nullable=True),
    sa.Column('luogo_nascita', sa.String(length=128), nullable=True),
    sa.Column('provincia_nascita', sa.String(length=128), nullable=True),
    sa.Column('stato_nascita', sa.String(length=128), nullable=True),
    sa.Column('descr_cittadinanza', sa.String(length=128), nullable=True),
    sa.Column('matricola', sa.String(length=128), nullable=True),
    sa.Column('comune_residenza', sa.String(length=128), nullable=True),
    sa.Column('provincia_residenza', sa.String(length=128), nullable=True),
    sa.Column('indirizzo_residenza', sa.String(length=128), nullable=True),
    sa.Column('via', sa.String(length=128), nullable=True),
    sa.Column('cap_residenza', sa.String(length=128), nullable=True),
    sa.Column('stato_alunno', sa.String(length=128), nullable=True),
    sa.Column('tipologia_stato_alunno', sa.String(length=128), nullable=True),
    sa.Column('data_inizio', sa.DateTime(), nullable=True),
    sa.Column('data_fine', sa.DateTime(), nullable=True),
    sa.Column('numero_volte_iscrizione', sa.Integer(), nullable=True),
    sa.Column('fornito_di', sa.String(length=128), nullable=True),
    sa.Column('scuola_provenienza', sa.String(length=128), nullable=True),
    sa.Column('posizione', sa.String(length=128), nullable=True),
    sa.Column('religione_cattolica', sa.String(length=128), nullable=True),
    sa.Column('attivita_alternativa', sa.String(length=128), nullable=True),
    sa.Column('educazione_fisica', sa.String(length=128), nullable=True),
    sa.Column('esito_finale', sa.String(length=128), nullable=True),
    sa.Column('esito_finale_norm', sa.String(length=128), nullable=True),
    sa.Column('esito_sospeso', sa.String(length=128), nullable=True),
    sa.Column('media_voti', sa.Float(), nullable=True),
    sa.Column('scuola_trasferimento', sa.String(length=128), nullable=True),
    sa.Column('punteggio_esame', sa.String(length=128), nullable=True),
    sa.Column('anno_corso', sa.Integer(), nullable=True),
    sa.Column('anno_sigla', sa.Integer(), nullable=True),
    sa.Column('sezione', sa.String(length=128), nullable=True),
    sa.Column('classe', sa.String(length=128), nullable=True),
    sa.Column('indirizzo_studi', sa.String(length=128), nullable=True),
    sa.Column('indirizzo_studi_norm', sa.String(length=128), nullable=True),
    sa.Column('classificazione_ministeriale', sa.String(length=128), nullable=True),
    sa.Column('indirizzo_ministeriale', sa.String(length=128), nullable=True),
    sa.Column('sede', sa.String(length=128), nullable=True),
    sa.Column('sede_norm', sa.String(length=128), nullable=True),
    sa.Column('scuola', sa.String(length=128), nullable=True),
    sa.Column('cod_meccanografico', sa.String(length=128), nullable=True),
    sa.Column('piano_studio', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('data_create', sa.DateTime(), nullable=True),
    sa.Column('data_update', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rel_alunno_strada',
    sa.Column('alunno_id', sa.Integer(), nullable=False),
    sa.Column('strada_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alunno_id'], ['alunni.id'], ),
    sa.ForeignKeyConstraint(['strada_id'], ['strada.id'], ),
    sa.PrimaryKeyConstraint('alunno_id', 'strada_id'),
    info={'bind_key': None}
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rel_alunno_strada')
    op.drop_table('alunni')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_stradario_nome_norm'), table_name='stradario')
    op.drop_index(op.f('ix_stradario_comune'), table_name='stradario')
    op.drop_table('stradario')
    op.drop_table('strada')
    op.drop_table('indirizzo')
    # ### end Alembic commands ###
